/* soapExchangeServiceBindingProxy.h
   Generated by gSOAP 2.8.23 from services.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapExchangeServiceBindingProxy_H
#define soapExchangeServiceBindingProxy_H
#include "soapH.h"

class SOAP_CMAC ExchangeServiceBindingProxy
{ public:
	struct soap *soap;
	bool soap_own;
	/// Endpoint URL of service 'ExchangeServiceBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Variables globally declared in services.h (non-static)
	/// Constructor
	ExchangeServiceBindingProxy();
	/// Constructor to use/share an engine state
	ExchangeServiceBindingProxy(struct soap*);
	/// Constructor with endpoint URL
	ExchangeServiceBindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	ExchangeServiceBindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	ExchangeServiceBindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	ExchangeServiceBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor deletes non-shared engine context only (use destroy() to delete deserialized data)
	virtual	~ExchangeServiceBindingProxy();
	/// Initializer used by constructors
	virtual	void ExchangeServiceBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Put SOAP Header in message
	virtual	void soap_header(enum ns1__DateTimePrecisionType *ns1__DateTimePrecision, ns1__ExchangeImpersonationType *ns1__ExchangeImpersonation, ns1__MailboxCultureType *ns1__MailboxCulture, ns1__ManagementRoleType *ns1__ManagementRole, _ns1__RequestServerVersion *ns1__RequestServerVersion, _ns1__ServerVersionInfo *ns1__ServerVersionInfo, ns1__TimeZoneContextType *ns1__TimeZoneContext);
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'ResolveNames' (returns error code or SOAP_OK)
	virtual	int ResolveNames(ews__ResolveNamesType *ews__ResolveNames, struct __ews__ResolveNamesResponse &_param_1) { return this->ResolveNames(NULL, NULL, ews__ResolveNames, _param_1); }
	virtual	int ResolveNames(const char *endpoint, const char *soap_action, ews__ResolveNamesType *ews__ResolveNames, struct __ews__ResolveNamesResponse &_param_1);

	/// Web service operation 'ExpandDL' (returns error code or SOAP_OK)
	virtual	int ExpandDL(ews__ExpandDLType *ews__ExpandDL, struct __ews__ExpandDLResponse &_param_2) { return this->ExpandDL(NULL, NULL, ews__ExpandDL, _param_2); }
	virtual	int ExpandDL(const char *endpoint, const char *soap_action, ews__ExpandDLType *ews__ExpandDL, struct __ews__ExpandDLResponse &_param_2);

	/// Web service operation 'GetServerTimeZones' (returns error code or SOAP_OK)
	virtual	int GetServerTimeZones(ews__GetServerTimeZonesType *ews__GetServerTimeZones, struct __ews__GetServerTimeZonesResponse &_param_3) { return this->GetServerTimeZones(NULL, NULL, ews__GetServerTimeZones, _param_3); }
	virtual	int GetServerTimeZones(const char *endpoint, const char *soap_action, ews__GetServerTimeZonesType *ews__GetServerTimeZones, struct __ews__GetServerTimeZonesResponse &_param_3);

	/// Web service operation 'FindFolder' (returns error code or SOAP_OK)
	virtual	int FindFolder(ews__FindFolderType *ews__FindFolder, struct __ews__FindFolderResponse &_param_4) { return this->FindFolder(NULL, NULL, ews__FindFolder, _param_4); }
	virtual	int FindFolder(const char *endpoint, const char *soap_action, ews__FindFolderType *ews__FindFolder, struct __ews__FindFolderResponse &_param_4);

	/// Web service operation 'FindItem' (returns error code or SOAP_OK)
	virtual	int FindItem(ews__FindItemType *ews__FindItem, struct __ews__FindItemResponse &_param_5) { return this->FindItem(NULL, NULL, ews__FindItem, _param_5); }
	virtual	int FindItem(const char *endpoint, const char *soap_action, ews__FindItemType *ews__FindItem, struct __ews__FindItemResponse &_param_5);

	/// Web service operation 'GetFolder' (returns error code or SOAP_OK)
	virtual	int GetFolder(ews__GetFolderType *ews__GetFolder, struct __ews__GetFolderResponse &_param_6) { return this->GetFolder(NULL, NULL, ews__GetFolder, _param_6); }
	virtual	int GetFolder(const char *endpoint, const char *soap_action, ews__GetFolderType *ews__GetFolder, struct __ews__GetFolderResponse &_param_6);

	/// Web service operation 'ConvertId' (returns error code or SOAP_OK)
	virtual	int ConvertId(ews__ConvertIdType *ews__ConvertId, struct __ews__ConvertIdResponse &_param_7) { return this->ConvertId(NULL, NULL, ews__ConvertId, _param_7); }
	virtual	int ConvertId(const char *endpoint, const char *soap_action, ews__ConvertIdType *ews__ConvertId, struct __ews__ConvertIdResponse &_param_7);

	/// Web service operation 'UploadItems' (returns error code or SOAP_OK)
	virtual	int UploadItems(ews__UploadItemsType *ews__UploadItems, struct __ews__UploadItemsResponse &_param_8) { return this->UploadItems(NULL, NULL, ews__UploadItems, _param_8); }
	virtual	int UploadItems(const char *endpoint, const char *soap_action, ews__UploadItemsType *ews__UploadItems, struct __ews__UploadItemsResponse &_param_8);

	/// Web service operation 'ExportItems' (returns error code or SOAP_OK)
	virtual	int ExportItems(ews__ExportItemsType *ews__ExportItems, struct __ews__ExportItemsResponse &_param_9) { return this->ExportItems(NULL, NULL, ews__ExportItems, _param_9); }
	virtual	int ExportItems(const char *endpoint, const char *soap_action, ews__ExportItemsType *ews__ExportItems, struct __ews__ExportItemsResponse &_param_9);

	/// Web service operation 'CreateFolderPath' (returns error code or SOAP_OK)
	virtual	int CreateFolderPath(ews__CreateFolderPathType *ews__CreateFolderPath, struct __ews__CreateFolderPathResponse &_param_10) { return this->CreateFolderPath(NULL, NULL, ews__CreateFolderPath, _param_10); }
	virtual	int CreateFolderPath(const char *endpoint, const char *soap_action, ews__CreateFolderPathType *ews__CreateFolderPath, struct __ews__CreateFolderPathResponse &_param_10);

	/// Web service operation 'CreateFolder' (returns error code or SOAP_OK)
	virtual	int CreateFolder(ews__CreateFolderType *ews__CreateFolder, struct __ews__CreateFolderResponse &_param_11) { return this->CreateFolder(NULL, NULL, ews__CreateFolder, _param_11); }
	virtual	int CreateFolder(const char *endpoint, const char *soap_action, ews__CreateFolderType *ews__CreateFolder, struct __ews__CreateFolderResponse &_param_11);

	/// Web service operation 'DeleteFolder' (returns error code or SOAP_OK)
	virtual	int DeleteFolder(ews__DeleteFolderType *ews__DeleteFolder, struct __ews__DeleteFolderResponse &_param_12) { return this->DeleteFolder(NULL, NULL, ews__DeleteFolder, _param_12); }
	virtual	int DeleteFolder(const char *endpoint, const char *soap_action, ews__DeleteFolderType *ews__DeleteFolder, struct __ews__DeleteFolderResponse &_param_12);

	/// Web service operation 'EmptyFolder' (returns error code or SOAP_OK)
	virtual	int EmptyFolder(ews__EmptyFolderType *ews__EmptyFolder, struct __ews__EmptyFolderResponse &_param_13) { return this->EmptyFolder(NULL, NULL, ews__EmptyFolder, _param_13); }
	virtual	int EmptyFolder(const char *endpoint, const char *soap_action, ews__EmptyFolderType *ews__EmptyFolder, struct __ews__EmptyFolderResponse &_param_13);

	/// Web service operation 'UpdateFolder' (returns error code or SOAP_OK)
	virtual	int UpdateFolder(ews__UpdateFolderType *ews__UpdateFolder, struct __ews__UpdateFolderResponse &_param_14) { return this->UpdateFolder(NULL, NULL, ews__UpdateFolder, _param_14); }
	virtual	int UpdateFolder(const char *endpoint, const char *soap_action, ews__UpdateFolderType *ews__UpdateFolder, struct __ews__UpdateFolderResponse &_param_14);

	/// Web service operation 'MoveFolder' (returns error code or SOAP_OK)
	virtual	int MoveFolder(ews__MoveFolderType *ews__MoveFolder, struct __ews__MoveFolderResponse &_param_15) { return this->MoveFolder(NULL, NULL, ews__MoveFolder, _param_15); }
	virtual	int MoveFolder(const char *endpoint, const char *soap_action, ews__MoveFolderType *ews__MoveFolder, struct __ews__MoveFolderResponse &_param_15);

	/// Web service operation 'CopyFolder' (returns error code or SOAP_OK)
	virtual	int CopyFolder(ews__CopyFolderType *ews__CopyFolder, struct __ews__CopyFolderResponse &_param_16) { return this->CopyFolder(NULL, NULL, ews__CopyFolder, _param_16); }
	virtual	int CopyFolder(const char *endpoint, const char *soap_action, ews__CopyFolderType *ews__CopyFolder, struct __ews__CopyFolderResponse &_param_16);

	/// Web service operation 'Subscribe' (returns error code or SOAP_OK)
	virtual	int Subscribe(ews__SubscribeType *ews__Subscribe, struct __ews__SubscribeResponse &_param_17) { return this->Subscribe(NULL, NULL, ews__Subscribe, _param_17); }
	virtual	int Subscribe(const char *endpoint, const char *soap_action, ews__SubscribeType *ews__Subscribe, struct __ews__SubscribeResponse &_param_17);

	/// Web service operation 'Unsubscribe' (returns error code or SOAP_OK)
	virtual	int Unsubscribe(ews__UnsubscribeType *ews__Unsubscribe, struct __ews__UnsubscribeResponse &_param_18) { return this->Unsubscribe(NULL, NULL, ews__Unsubscribe, _param_18); }
	virtual	int Unsubscribe(const char *endpoint, const char *soap_action, ews__UnsubscribeType *ews__Unsubscribe, struct __ews__UnsubscribeResponse &_param_18);

	/// Web service operation 'GetEvents' (returns error code or SOAP_OK)
	virtual	int GetEvents(ews__GetEventsType *ews__GetEvents, struct __ews__GetEventsResponse &_param_19) { return this->GetEvents(NULL, NULL, ews__GetEvents, _param_19); }
	virtual	int GetEvents(const char *endpoint, const char *soap_action, ews__GetEventsType *ews__GetEvents, struct __ews__GetEventsResponse &_param_19);

	/// Web service operation 'GetStreamingEvents' (returns error code or SOAP_OK)
	virtual	int GetStreamingEvents(ews__GetStreamingEventsType *ews__GetStreamingEvents, struct __ews__GetStreamingEventsResponse &_param_20) { return this->GetStreamingEvents(NULL, NULL, ews__GetStreamingEvents, _param_20); }
	virtual	int GetStreamingEvents(const char *endpoint, const char *soap_action, ews__GetStreamingEventsType *ews__GetStreamingEvents, struct __ews__GetStreamingEventsResponse &_param_20);

	/// Web service operation 'SyncFolderHierarchy' (returns error code or SOAP_OK)
	virtual	int SyncFolderHierarchy(ews__SyncFolderHierarchyType *ews__SyncFolderHierarchy, struct __ews__SyncFolderHierarchyResponse &_param_21) { return this->SyncFolderHierarchy(NULL, NULL, ews__SyncFolderHierarchy, _param_21); }
	virtual	int SyncFolderHierarchy(const char *endpoint, const char *soap_action, ews__SyncFolderHierarchyType *ews__SyncFolderHierarchy, struct __ews__SyncFolderHierarchyResponse &_param_21);

	/// Web service operation 'SyncFolderItems' (returns error code or SOAP_OK)
	virtual	int SyncFolderItems(ews__SyncFolderItemsType *ews__SyncFolderItems, struct __ews__SyncFolderItemsResponse &_param_22) { return this->SyncFolderItems(NULL, NULL, ews__SyncFolderItems, _param_22); }
	virtual	int SyncFolderItems(const char *endpoint, const char *soap_action, ews__SyncFolderItemsType *ews__SyncFolderItems, struct __ews__SyncFolderItemsResponse &_param_22);

	/// Web service operation 'GetItem' (returns error code or SOAP_OK)
	virtual	int GetItem(ews__GetItemType *ews__GetItem, struct __ews__GetItemResponse &_param_23) { return this->GetItem(NULL, NULL, ews__GetItem, _param_23); }
	virtual	int GetItem(const char *endpoint, const char *soap_action, ews__GetItemType *ews__GetItem, struct __ews__GetItemResponse &_param_23);

	/// Web service operation 'CreateItem' (returns error code or SOAP_OK)
	virtual	int CreateItem(ews__CreateItemType *ews__CreateItem, struct __ews__CreateItemResponse &_param_24) { return this->CreateItem(NULL, NULL, ews__CreateItem, _param_24); }
	virtual	int CreateItem(const char *endpoint, const char *soap_action, ews__CreateItemType *ews__CreateItem, struct __ews__CreateItemResponse &_param_24);

	/// Web service operation 'DeleteItem' (returns error code or SOAP_OK)
	virtual	int DeleteItem(ews__DeleteItemType *ews__DeleteItem, struct __ews__DeleteItemResponse &_param_25) { return this->DeleteItem(NULL, NULL, ews__DeleteItem, _param_25); }
	virtual	int DeleteItem(const char *endpoint, const char *soap_action, ews__DeleteItemType *ews__DeleteItem, struct __ews__DeleteItemResponse &_param_25);

	/// Web service operation 'UpdateItem' (returns error code or SOAP_OK)
	virtual	int UpdateItem(ews__UpdateItemType *ews__UpdateItem, struct __ews__UpdateItemResponse &_param_26) { return this->UpdateItem(NULL, NULL, ews__UpdateItem, _param_26); }
	virtual	int UpdateItem(const char *endpoint, const char *soap_action, ews__UpdateItemType *ews__UpdateItem, struct __ews__UpdateItemResponse &_param_26);

	/// Web service operation 'UpdateItemInRecoverableItems' (returns error code or SOAP_OK)
	virtual	int UpdateItemInRecoverableItems(ews__UpdateItemInRecoverableItemsType *ews__UpdateItemInRecoverableItems, struct __ews__UpdateItemInRecoverableItemsResponse &_param_27) { return this->UpdateItemInRecoverableItems(NULL, NULL, ews__UpdateItemInRecoverableItems, _param_27); }
	virtual	int UpdateItemInRecoverableItems(const char *endpoint, const char *soap_action, ews__UpdateItemInRecoverableItemsType *ews__UpdateItemInRecoverableItems, struct __ews__UpdateItemInRecoverableItemsResponse &_param_27);

	/// Web service operation 'SendItem' (returns error code or SOAP_OK)
	virtual	int SendItem(ews__SendItemType *ews__SendItem, struct __ews__SendItemResponse &_param_28) { return this->SendItem(NULL, NULL, ews__SendItem, _param_28); }
	virtual	int SendItem(const char *endpoint, const char *soap_action, ews__SendItemType *ews__SendItem, struct __ews__SendItemResponse &_param_28);

	/// Web service operation 'MoveItem' (returns error code or SOAP_OK)
	virtual	int MoveItem(ews__MoveItemType *ews__MoveItem, struct __ews__MoveItemResponse &_param_29) { return this->MoveItem(NULL, NULL, ews__MoveItem, _param_29); }
	virtual	int MoveItem(const char *endpoint, const char *soap_action, ews__MoveItemType *ews__MoveItem, struct __ews__MoveItemResponse &_param_29);

	/// Web service operation 'CopyItem' (returns error code or SOAP_OK)
	virtual	int CopyItem(ews__CopyItemType *ews__CopyItem, struct __ews__CopyItemResponse &_param_30) { return this->CopyItem(NULL, NULL, ews__CopyItem, _param_30); }
	virtual	int CopyItem(const char *endpoint, const char *soap_action, ews__CopyItemType *ews__CopyItem, struct __ews__CopyItemResponse &_param_30);

	/// Web service operation 'ArchiveItem' (returns error code or SOAP_OK)
	virtual	int ArchiveItem(ews__ArchiveItemType *ews__ArchiveItem, struct __ews__ArchiveItemResponse &_param_31) { return this->ArchiveItem(NULL, NULL, ews__ArchiveItem, _param_31); }
	virtual	int ArchiveItem(const char *endpoint, const char *soap_action, ews__ArchiveItemType *ews__ArchiveItem, struct __ews__ArchiveItemResponse &_param_31);

	/// Web service operation 'CreateAttachment' (returns error code or SOAP_OK)
	virtual	int CreateAttachment(ews__CreateAttachmentType *ews__CreateAttachment, struct __ews__CreateAttachmentResponse &_param_32) { return this->CreateAttachment(NULL, NULL, ews__CreateAttachment, _param_32); }
	virtual	int CreateAttachment(const char *endpoint, const char *soap_action, ews__CreateAttachmentType *ews__CreateAttachment, struct __ews__CreateAttachmentResponse &_param_32);

	/// Web service operation 'DeleteAttachment' (returns error code or SOAP_OK)
	virtual	int DeleteAttachment(ews__DeleteAttachmentType *ews__DeleteAttachment, struct __ews__DeleteAttachmentResponse &_param_33) { return this->DeleteAttachment(NULL, NULL, ews__DeleteAttachment, _param_33); }
	virtual	int DeleteAttachment(const char *endpoint, const char *soap_action, ews__DeleteAttachmentType *ews__DeleteAttachment, struct __ews__DeleteAttachmentResponse &_param_33);

	/// Web service operation 'GetAttachment' (returns error code or SOAP_OK)
	virtual	int GetAttachment(ews__GetAttachmentType *ews__GetAttachment, struct __ews__GetAttachmentResponse &_param_34) { return this->GetAttachment(NULL, NULL, ews__GetAttachment, _param_34); }
	virtual	int GetAttachment(const char *endpoint, const char *soap_action, ews__GetAttachmentType *ews__GetAttachment, struct __ews__GetAttachmentResponse &_param_34);

	/// Web service operation 'GetClientAccessToken' (returns error code or SOAP_OK)
	virtual	int GetClientAccessToken(ews__GetClientAccessTokenType *ews__GetClientAccessToken, struct __ews__GetClientAccessTokenResponse &_param_35) { return this->GetClientAccessToken(NULL, NULL, ews__GetClientAccessToken, _param_35); }
	virtual	int GetClientAccessToken(const char *endpoint, const char *soap_action, ews__GetClientAccessTokenType *ews__GetClientAccessToken, struct __ews__GetClientAccessTokenResponse &_param_35);

	/// Web service operation 'CreateManagedFolder' (returns error code or SOAP_OK)
	virtual	int CreateManagedFolder(ews__CreateManagedFolderRequestType *ews__CreateManagedFolder, struct __ews__CreateManagedFolderResponse &_param_36) { return this->CreateManagedFolder(NULL, NULL, ews__CreateManagedFolder, _param_36); }
	virtual	int CreateManagedFolder(const char *endpoint, const char *soap_action, ews__CreateManagedFolderRequestType *ews__CreateManagedFolder, struct __ews__CreateManagedFolderResponse &_param_36);

	/// Web service operation 'GetDelegate' (returns error code or SOAP_OK)
	virtual	int GetDelegate(ews__GetDelegateType *ews__GetDelegate, struct __ews__GetDelegateResponse &_param_37) { return this->GetDelegate(NULL, NULL, ews__GetDelegate, _param_37); }
	virtual	int GetDelegate(const char *endpoint, const char *soap_action, ews__GetDelegateType *ews__GetDelegate, struct __ews__GetDelegateResponse &_param_37);

	/// Web service operation 'AddDelegate' (returns error code or SOAP_OK)
	virtual	int AddDelegate(ews__AddDelegateType *ews__AddDelegate, struct __ews__AddDelegateResponse &_param_38) { return this->AddDelegate(NULL, NULL, ews__AddDelegate, _param_38); }
	virtual	int AddDelegate(const char *endpoint, const char *soap_action, ews__AddDelegateType *ews__AddDelegate, struct __ews__AddDelegateResponse &_param_38);

	/// Web service operation 'RemoveDelegate' (returns error code or SOAP_OK)
	virtual	int RemoveDelegate(ews__RemoveDelegateType *ews__RemoveDelegate, struct __ews__RemoveDelegateResponse &_param_39) { return this->RemoveDelegate(NULL, NULL, ews__RemoveDelegate, _param_39); }
	virtual	int RemoveDelegate(const char *endpoint, const char *soap_action, ews__RemoveDelegateType *ews__RemoveDelegate, struct __ews__RemoveDelegateResponse &_param_39);

	/// Web service operation 'UpdateDelegate' (returns error code or SOAP_OK)
	virtual	int UpdateDelegate(ews__UpdateDelegateType *ews__UpdateDelegate, struct __ews__UpdateDelegateResponse &_param_40) { return this->UpdateDelegate(NULL, NULL, ews__UpdateDelegate, _param_40); }
	virtual	int UpdateDelegate(const char *endpoint, const char *soap_action, ews__UpdateDelegateType *ews__UpdateDelegate, struct __ews__UpdateDelegateResponse &_param_40);

	/// Web service operation 'CreateUserConfiguration' (returns error code or SOAP_OK)
	virtual	int CreateUserConfiguration(ews__CreateUserConfigurationType *ews__CreateUserConfiguration, struct __ews__CreateUserConfigurationResponse &_param_41) { return this->CreateUserConfiguration(NULL, NULL, ews__CreateUserConfiguration, _param_41); }
	virtual	int CreateUserConfiguration(const char *endpoint, const char *soap_action, ews__CreateUserConfigurationType *ews__CreateUserConfiguration, struct __ews__CreateUserConfigurationResponse &_param_41);

	/// Web service operation 'DeleteUserConfiguration' (returns error code or SOAP_OK)
	virtual	int DeleteUserConfiguration(ews__DeleteUserConfigurationType *ews__DeleteUserConfiguration, struct __ews__DeleteUserConfigurationResponse &_param_42) { return this->DeleteUserConfiguration(NULL, NULL, ews__DeleteUserConfiguration, _param_42); }
	virtual	int DeleteUserConfiguration(const char *endpoint, const char *soap_action, ews__DeleteUserConfigurationType *ews__DeleteUserConfiguration, struct __ews__DeleteUserConfigurationResponse &_param_42);

	/// Web service operation 'GetUserConfiguration' (returns error code or SOAP_OK)
	virtual	int GetUserConfiguration(ews__GetUserConfigurationType *ews__GetUserConfiguration, struct __ews__GetUserConfigurationResponse &_param_43) { return this->GetUserConfiguration(NULL, NULL, ews__GetUserConfiguration, _param_43); }
	virtual	int GetUserConfiguration(const char *endpoint, const char *soap_action, ews__GetUserConfigurationType *ews__GetUserConfiguration, struct __ews__GetUserConfigurationResponse &_param_43);

	/// Web service operation 'UpdateUserConfiguration' (returns error code or SOAP_OK)
	virtual	int UpdateUserConfiguration(ews__UpdateUserConfigurationType *ews__UpdateUserConfiguration, struct __ews__UpdateUserConfigurationResponse &_param_44) { return this->UpdateUserConfiguration(NULL, NULL, ews__UpdateUserConfiguration, _param_44); }
	virtual	int UpdateUserConfiguration(const char *endpoint, const char *soap_action, ews__UpdateUserConfigurationType *ews__UpdateUserConfiguration, struct __ews__UpdateUserConfigurationResponse &_param_44);

	/// Web service operation 'GetUserAvailability' (returns error code or SOAP_OK)
	virtual	int GetUserAvailability(ews__GetUserAvailabilityRequestType *ews__GetUserAvailabilityRequest, struct __ews__GetUserAvailabilityResponse &_param_45) { return this->GetUserAvailability(NULL, NULL, ews__GetUserAvailabilityRequest, _param_45); }
	virtual	int GetUserAvailability(const char *endpoint, const char *soap_action, ews__GetUserAvailabilityRequestType *ews__GetUserAvailabilityRequest, struct __ews__GetUserAvailabilityResponse &_param_45);

	/// Web service operation 'GetUserOofSettings' (returns error code or SOAP_OK)
	virtual	int GetUserOofSettings(ews__GetUserOofSettingsRequest *ews__GetUserOofSettingsRequest_, struct __ews__GetUserOofSettingsResponse &_param_46) { return this->GetUserOofSettings(NULL, NULL, ews__GetUserOofSettingsRequest_, _param_46); }
	virtual	int GetUserOofSettings(const char *endpoint, const char *soap_action, ews__GetUserOofSettingsRequest *ews__GetUserOofSettingsRequest_, struct __ews__GetUserOofSettingsResponse &_param_46);

	/// Web service operation 'SetUserOofSettings' (returns error code or SOAP_OK)
	virtual	int SetUserOofSettings(ews__SetUserOofSettingsRequest *ews__SetUserOofSettingsRequest_, struct __ews__SetUserOofSettingsResponse &_param_47) { return this->SetUserOofSettings(NULL, NULL, ews__SetUserOofSettingsRequest_, _param_47); }
	virtual	int SetUserOofSettings(const char *endpoint, const char *soap_action, ews__SetUserOofSettingsRequest *ews__SetUserOofSettingsRequest_, struct __ews__SetUserOofSettingsResponse &_param_47);

	/// Web service operation 'GetServiceConfiguration' (returns error code or SOAP_OK)
	virtual	int GetServiceConfiguration(ews__GetServiceConfigurationType *ews__GetServiceConfiguration, struct __ews__GetServiceConfigurationResponse &_param_48) { return this->GetServiceConfiguration(NULL, NULL, ews__GetServiceConfiguration, _param_48); }
	virtual	int GetServiceConfiguration(const char *endpoint, const char *soap_action, ews__GetServiceConfigurationType *ews__GetServiceConfiguration, struct __ews__GetServiceConfigurationResponse &_param_48);

	/// Web service operation 'GetMailTips' (returns error code or SOAP_OK)
	virtual	int GetMailTips(ews__GetMailTipsType *ews__GetMailTips, struct __ews__GetMailTipsResponse &_param_49) { return this->GetMailTips(NULL, NULL, ews__GetMailTips, _param_49); }
	virtual	int GetMailTips(const char *endpoint, const char *soap_action, ews__GetMailTipsType *ews__GetMailTips, struct __ews__GetMailTipsResponse &_param_49);

	/// Web service operation 'PlayOnPhone' (returns error code or SOAP_OK)
	virtual	int PlayOnPhone(ews__PlayOnPhoneType *ews__PlayOnPhone, struct __ews__PlayOnPhoneResponse &_param_50) { return this->PlayOnPhone(NULL, NULL, ews__PlayOnPhone, _param_50); }
	virtual	int PlayOnPhone(const char *endpoint, const char *soap_action, ews__PlayOnPhoneType *ews__PlayOnPhone, struct __ews__PlayOnPhoneResponse &_param_50);

	/// Web service operation 'GetPhoneCallInformation' (returns error code or SOAP_OK)
	virtual	int GetPhoneCallInformation(ews__GetPhoneCallInformationType *ews__GetPhoneCallInformation, struct __ews__GetPhoneCallInformationResponse &_param_51) { return this->GetPhoneCallInformation(NULL, NULL, ews__GetPhoneCallInformation, _param_51); }
	virtual	int GetPhoneCallInformation(const char *endpoint, const char *soap_action, ews__GetPhoneCallInformationType *ews__GetPhoneCallInformation, struct __ews__GetPhoneCallInformationResponse &_param_51);

	/// Web service operation 'DisconnectPhoneCall' (returns error code or SOAP_OK)
	virtual	int DisconnectPhoneCall(ews__DisconnectPhoneCallType *ews__DisconnectPhoneCall, struct __ews__DisconnectPhoneCallResponse &_param_52) { return this->DisconnectPhoneCall(NULL, NULL, ews__DisconnectPhoneCall, _param_52); }
	virtual	int DisconnectPhoneCall(const char *endpoint, const char *soap_action, ews__DisconnectPhoneCallType *ews__DisconnectPhoneCall, struct __ews__DisconnectPhoneCallResponse &_param_52);

	/// Web service operation 'GetSharingMetadata' (returns error code or SOAP_OK)
	virtual	int GetSharingMetadata(ews__GetSharingMetadataType *ews__GetSharingMetadata, struct __ews__GetSharingMetadataResponse &_param_53) { return this->GetSharingMetadata(NULL, NULL, ews__GetSharingMetadata, _param_53); }
	virtual	int GetSharingMetadata(const char *endpoint, const char *soap_action, ews__GetSharingMetadataType *ews__GetSharingMetadata, struct __ews__GetSharingMetadataResponse &_param_53);

	/// Web service operation 'RefreshSharingFolder' (returns error code or SOAP_OK)
	virtual	int RefreshSharingFolder(ews__RefreshSharingFolderType *ews__RefreshSharingFolder, struct __ews__RefreshSharingFolderResponse &_param_54) { return this->RefreshSharingFolder(NULL, NULL, ews__RefreshSharingFolder, _param_54); }
	virtual	int RefreshSharingFolder(const char *endpoint, const char *soap_action, ews__RefreshSharingFolderType *ews__RefreshSharingFolder, struct __ews__RefreshSharingFolderResponse &_param_54);

	/// Web service operation 'GetSharingFolder' (returns error code or SOAP_OK)
	virtual	int GetSharingFolder(ews__GetSharingFolderType *ews__GetSharingFolder, struct __ews__GetSharingFolderResponse &_param_55) { return this->GetSharingFolder(NULL, NULL, ews__GetSharingFolder, _param_55); }
	virtual	int GetSharingFolder(const char *endpoint, const char *soap_action, ews__GetSharingFolderType *ews__GetSharingFolder, struct __ews__GetSharingFolderResponse &_param_55);

	/// Web service operation 'SetTeamMailbox' (returns error code or SOAP_OK)
	virtual	int SetTeamMailbox(ews__SetTeamMailboxRequestType *ews__SetTeamMailbox, struct __ews__SetTeamMailboxResponse &_param_56) { return this->SetTeamMailbox(NULL, NULL, ews__SetTeamMailbox, _param_56); }
	virtual	int SetTeamMailbox(const char *endpoint, const char *soap_action, ews__SetTeamMailboxRequestType *ews__SetTeamMailbox, struct __ews__SetTeamMailboxResponse &_param_56);

	/// Web service operation 'UnpinTeamMailbox' (returns error code or SOAP_OK)
	virtual	int UnpinTeamMailbox(ews__UnpinTeamMailboxRequestType *ews__UnpinTeamMailbox, struct __ews__UnpinTeamMailboxResponse &_param_57) { return this->UnpinTeamMailbox(NULL, NULL, ews__UnpinTeamMailbox, _param_57); }
	virtual	int UnpinTeamMailbox(const char *endpoint, const char *soap_action, ews__UnpinTeamMailboxRequestType *ews__UnpinTeamMailbox, struct __ews__UnpinTeamMailboxResponse &_param_57);

	/// Web service operation 'GetRoomLists' (returns error code or SOAP_OK)
	virtual	int GetRoomLists(ews__GetRoomListsType *ews__GetRoomLists, struct __ews__GetRoomListsResponse &_param_58) { return this->GetRoomLists(NULL, NULL, ews__GetRoomLists, _param_58); }
	virtual	int GetRoomLists(const char *endpoint, const char *soap_action, ews__GetRoomListsType *ews__GetRoomLists, struct __ews__GetRoomListsResponse &_param_58);

	/// Web service operation 'GetRooms' (returns error code or SOAP_OK)
	virtual	int GetRooms(ews__GetRoomsType *ews__GetRooms, struct __ews__GetRoomsResponse &_param_59) { return this->GetRooms(NULL, NULL, ews__GetRooms, _param_59); }
	virtual	int GetRooms(const char *endpoint, const char *soap_action, ews__GetRoomsType *ews__GetRooms, struct __ews__GetRoomsResponse &_param_59);

	/// Web service operation 'FindMessageTrackingReport' (returns error code or SOAP_OK)
	virtual	int FindMessageTrackingReport(ews__FindMessageTrackingReportRequestType *ews__FindMessageTrackingReport, struct __ews__FindMessageTrackingReportResponse &_param_60) { return this->FindMessageTrackingReport(NULL, NULL, ews__FindMessageTrackingReport, _param_60); }
	virtual	int FindMessageTrackingReport(const char *endpoint, const char *soap_action, ews__FindMessageTrackingReportRequestType *ews__FindMessageTrackingReport, struct __ews__FindMessageTrackingReportResponse &_param_60);

	/// Web service operation 'GetMessageTrackingReport' (returns error code or SOAP_OK)
	virtual	int GetMessageTrackingReport(ews__GetMessageTrackingReportRequestType *ews__GetMessageTrackingReport, struct __ews__GetMessageTrackingReportResponse &_param_61) { return this->GetMessageTrackingReport(NULL, NULL, ews__GetMessageTrackingReport, _param_61); }
	virtual	int GetMessageTrackingReport(const char *endpoint, const char *soap_action, ews__GetMessageTrackingReportRequestType *ews__GetMessageTrackingReport, struct __ews__GetMessageTrackingReportResponse &_param_61);

	/// Web service operation 'FindConversation' (returns error code or SOAP_OK)
	virtual	int FindConversation(ews__FindConversationType *ews__FindConversation, struct __ews__FindConversationResponse &_param_62) { return this->FindConversation(NULL, NULL, ews__FindConversation, _param_62); }
	virtual	int FindConversation(const char *endpoint, const char *soap_action, ews__FindConversationType *ews__FindConversation, struct __ews__FindConversationResponse &_param_62);

	/// Web service operation 'ApplyConversationAction' (returns error code or SOAP_OK)
	virtual	int ApplyConversationAction(ews__ApplyConversationActionType *ews__ApplyConversationAction, struct __ews__ApplyConversationActionResponse &_param_63) { return this->ApplyConversationAction(NULL, NULL, ews__ApplyConversationAction, _param_63); }
	virtual	int ApplyConversationAction(const char *endpoint, const char *soap_action, ews__ApplyConversationActionType *ews__ApplyConversationAction, struct __ews__ApplyConversationActionResponse &_param_63);

	/// Web service operation 'GetConversationItems' (returns error code or SOAP_OK)
	virtual	int GetConversationItems(ews__GetConversationItemsType *ews__GetConversationItems, struct __ews__GetConversationItemsResponse &_param_64) { return this->GetConversationItems(NULL, NULL, ews__GetConversationItems, _param_64); }
	virtual	int GetConversationItems(const char *endpoint, const char *soap_action, ews__GetConversationItemsType *ews__GetConversationItems, struct __ews__GetConversationItemsResponse &_param_64);

	/// Web service operation 'FindPeople' (returns error code or SOAP_OK)
	virtual	int FindPeople(ews__FindPeopleType *ews__FindPeople, struct __ews__FindPeopleResponse &_param_65) { return this->FindPeople(NULL, NULL, ews__FindPeople, _param_65); }
	virtual	int FindPeople(const char *endpoint, const char *soap_action, ews__FindPeopleType *ews__FindPeople, struct __ews__FindPeopleResponse &_param_65);

	/// Web service operation 'GetPersona' (returns error code or SOAP_OK)
	virtual	int GetPersona(ews__GetPersonaType *ews__GetPersona, struct __ews__GetPersonaResponse &_param_66) { return this->GetPersona(NULL, NULL, ews__GetPersona, _param_66); }
	virtual	int GetPersona(const char *endpoint, const char *soap_action, ews__GetPersonaType *ews__GetPersona, struct __ews__GetPersonaResponse &_param_66);

	/// Web service operation 'GetInboxRules' (returns error code or SOAP_OK)
	virtual	int GetInboxRules(ews__GetInboxRulesRequestType *ews__GetInboxRules, struct __ews__GetInboxRulesResponse &_param_67) { return this->GetInboxRules(NULL, NULL, ews__GetInboxRules, _param_67); }
	virtual	int GetInboxRules(const char *endpoint, const char *soap_action, ews__GetInboxRulesRequestType *ews__GetInboxRules, struct __ews__GetInboxRulesResponse &_param_67);

	/// Web service operation 'UpdateInboxRules' (returns error code or SOAP_OK)
	virtual	int UpdateInboxRules(ews__UpdateInboxRulesRequestType *ews__UpdateInboxRules, struct __ews__UpdateInboxRulesResponse &_param_68) { return this->UpdateInboxRules(NULL, NULL, ews__UpdateInboxRules, _param_68); }
	virtual	int UpdateInboxRules(const char *endpoint, const char *soap_action, ews__UpdateInboxRulesRequestType *ews__UpdateInboxRules, struct __ews__UpdateInboxRulesResponse &_param_68);

	/// Web service operation 'GetPasswordExpirationDate' (returns error code or SOAP_OK)
	virtual	int GetPasswordExpirationDate(ews__GetPasswordExpirationDateType *ews__GetPasswordExpirationDate, struct __ews__GetPasswordExpirationDateResponse &_param_69) { return this->GetPasswordExpirationDate(NULL, NULL, ews__GetPasswordExpirationDate, _param_69); }
	virtual	int GetPasswordExpirationDate(const char *endpoint, const char *soap_action, ews__GetPasswordExpirationDateType *ews__GetPasswordExpirationDate, struct __ews__GetPasswordExpirationDateResponse &_param_69);

	/// Web service operation 'GetDiscoverySearchConfiguration' (returns error code or SOAP_OK)
	virtual	int GetDiscoverySearchConfiguration(ews__GetDiscoverySearchConfigurationType *ews__GetDiscoverySearchConfiguration, struct __ews__GetDiscoverySearchConfigurationResponse &_param_70) { return this->GetDiscoverySearchConfiguration(NULL, NULL, ews__GetDiscoverySearchConfiguration, _param_70); }
	virtual	int GetDiscoverySearchConfiguration(const char *endpoint, const char *soap_action, ews__GetDiscoverySearchConfigurationType *ews__GetDiscoverySearchConfiguration, struct __ews__GetDiscoverySearchConfigurationResponse &_param_70);

	/// Web service operation 'GetSearchableMailboxes' (returns error code or SOAP_OK)
	virtual	int GetSearchableMailboxes(ews__GetSearchableMailboxesType *ews__GetSearchableMailboxes, struct __ews__GetSearchableMailboxesResponse &_param_71) { return this->GetSearchableMailboxes(NULL, NULL, ews__GetSearchableMailboxes, _param_71); }
	virtual	int GetSearchableMailboxes(const char *endpoint, const char *soap_action, ews__GetSearchableMailboxesType *ews__GetSearchableMailboxes, struct __ews__GetSearchableMailboxesResponse &_param_71);

	/// Web service operation 'SearchMailboxes' (returns error code or SOAP_OK)
	virtual	int SearchMailboxes(ews__SearchMailboxesType *ews__SearchMailboxes, struct __ews__SearchMailboxesResponse &_param_72) { return this->SearchMailboxes(NULL, NULL, ews__SearchMailboxes, _param_72); }
	virtual	int SearchMailboxes(const char *endpoint, const char *soap_action, ews__SearchMailboxesType *ews__SearchMailboxes, struct __ews__SearchMailboxesResponse &_param_72);

	/// Web service operation 'GetHoldOnMailboxes' (returns error code or SOAP_OK)
	virtual	int GetHoldOnMailboxes(ews__GetHoldOnMailboxesType *ews__GetHoldOnMailboxes, struct __ews__GetHoldOnMailboxesResponse &_param_73) { return this->GetHoldOnMailboxes(NULL, NULL, ews__GetHoldOnMailboxes, _param_73); }
	virtual	int GetHoldOnMailboxes(const char *endpoint, const char *soap_action, ews__GetHoldOnMailboxesType *ews__GetHoldOnMailboxes, struct __ews__GetHoldOnMailboxesResponse &_param_73);

	/// Web service operation 'SetHoldOnMailboxes' (returns error code or SOAP_OK)
	virtual	int SetHoldOnMailboxes(ews__SetHoldOnMailboxesType *ews__SetHoldOnMailboxes, struct __ews__SetHoldOnMailboxesResponse &_param_74) { return this->SetHoldOnMailboxes(NULL, NULL, ews__SetHoldOnMailboxes, _param_74); }
	virtual	int SetHoldOnMailboxes(const char *endpoint, const char *soap_action, ews__SetHoldOnMailboxesType *ews__SetHoldOnMailboxes, struct __ews__SetHoldOnMailboxesResponse &_param_74);

	/// Web service operation 'GetNonIndexableItemStatistics' (returns error code or SOAP_OK)
	virtual	int GetNonIndexableItemStatistics(ews__GetNonIndexableItemStatisticsType *ews__GetNonIndexableItemStatistics, struct __ews__GetNonIndexableItemStatisticsResponse &_param_75) { return this->GetNonIndexableItemStatistics(NULL, NULL, ews__GetNonIndexableItemStatistics, _param_75); }
	virtual	int GetNonIndexableItemStatistics(const char *endpoint, const char *soap_action, ews__GetNonIndexableItemStatisticsType *ews__GetNonIndexableItemStatistics, struct __ews__GetNonIndexableItemStatisticsResponse &_param_75);

	/// Web service operation 'GetNonIndexableItemDetails' (returns error code or SOAP_OK)
	virtual	int GetNonIndexableItemDetails(ews__GetNonIndexableItemDetailsType *ews__GetNonIndexableItemDetails, struct __ews__GetNonIndexableItemDetailsResponse &_param_76) { return this->GetNonIndexableItemDetails(NULL, NULL, ews__GetNonIndexableItemDetails, _param_76); }
	virtual	int GetNonIndexableItemDetails(const char *endpoint, const char *soap_action, ews__GetNonIndexableItemDetailsType *ews__GetNonIndexableItemDetails, struct __ews__GetNonIndexableItemDetailsResponse &_param_76);

	/// Web service operation 'MarkAllItemsAsRead' (returns error code or SOAP_OK)
	virtual	int MarkAllItemsAsRead(ews__MarkAllItemsAsReadType *ews__MarkAllItemsAsRead, struct __ews__MarkAllItemsAsReadResponse &_param_77) { return this->MarkAllItemsAsRead(NULL, NULL, ews__MarkAllItemsAsRead, _param_77); }
	virtual	int MarkAllItemsAsRead(const char *endpoint, const char *soap_action, ews__MarkAllItemsAsReadType *ews__MarkAllItemsAsRead, struct __ews__MarkAllItemsAsReadResponse &_param_77);

	/// Web service operation 'MarkAsJunk' (returns error code or SOAP_OK)
	virtual	int MarkAsJunk(ews__MarkAsJunkType *ews__MarkAsJunk, struct __ews__MarkAsJunkResponse &_param_78) { return this->MarkAsJunk(NULL, NULL, ews__MarkAsJunk, _param_78); }
	virtual	int MarkAsJunk(const char *endpoint, const char *soap_action, ews__MarkAsJunkType *ews__MarkAsJunk, struct __ews__MarkAsJunkResponse &_param_78);

	/// Web service operation 'GetAppManifests' (returns error code or SOAP_OK)
	virtual	int GetAppManifests(ews__GetAppManifestsType *ews__GetAppManifests, struct __ews__GetAppManifestsResponse &_param_79) { return this->GetAppManifests(NULL, NULL, ews__GetAppManifests, _param_79); }
	virtual	int GetAppManifests(const char *endpoint, const char *soap_action, ews__GetAppManifestsType *ews__GetAppManifests, struct __ews__GetAppManifestsResponse &_param_79);

	/// Web service operation 'AddNewImContactToGroup' (returns error code or SOAP_OK)
	virtual	int AddNewImContactToGroup(ews__AddNewImContactToGroupType *ews__AddNewImContactToGroup, struct __ews__AddNewImContactToGroupResponse &_param_80) { return this->AddNewImContactToGroup(NULL, NULL, ews__AddNewImContactToGroup, _param_80); }
	virtual	int AddNewImContactToGroup(const char *endpoint, const char *soap_action, ews__AddNewImContactToGroupType *ews__AddNewImContactToGroup, struct __ews__AddNewImContactToGroupResponse &_param_80);

	/// Web service operation 'AddNewTelUriContactToGroup' (returns error code or SOAP_OK)
	virtual	int AddNewTelUriContactToGroup(ews__AddNewTelUriContactToGroupType *ews__AddNewTelUriContactToGroup, struct __ews__AddNewTelUriContactToGroupResponse &_param_81) { return this->AddNewTelUriContactToGroup(NULL, NULL, ews__AddNewTelUriContactToGroup, _param_81); }
	virtual	int AddNewTelUriContactToGroup(const char *endpoint, const char *soap_action, ews__AddNewTelUriContactToGroupType *ews__AddNewTelUriContactToGroup, struct __ews__AddNewTelUriContactToGroupResponse &_param_81);

	/// Web service operation 'AddImContactToGroup' (returns error code or SOAP_OK)
	virtual	int AddImContactToGroup(ews__AddImContactToGroupType *ews__AddImContactToGroup, struct __ews__AddImContactToGroupResponse &_param_82) { return this->AddImContactToGroup(NULL, NULL, ews__AddImContactToGroup, _param_82); }
	virtual	int AddImContactToGroup(const char *endpoint, const char *soap_action, ews__AddImContactToGroupType *ews__AddImContactToGroup, struct __ews__AddImContactToGroupResponse &_param_82);

	/// Web service operation 'RemoveImContactFromGroup' (returns error code or SOAP_OK)
	virtual	int RemoveImContactFromGroup(ews__RemoveImContactFromGroupType *ews__RemoveImContactFromGroup, struct __ews__RemoveImContactFromGroupResponse &_param_83) { return this->RemoveImContactFromGroup(NULL, NULL, ews__RemoveImContactFromGroup, _param_83); }
	virtual	int RemoveImContactFromGroup(const char *endpoint, const char *soap_action, ews__RemoveImContactFromGroupType *ews__RemoveImContactFromGroup, struct __ews__RemoveImContactFromGroupResponse &_param_83);

	/// Web service operation 'AddImGroup' (returns error code or SOAP_OK)
	virtual	int AddImGroup(ews__AddImGroupType *ews__AddImGroup, struct __ews__AddImGroupResponse &_param_84) { return this->AddImGroup(NULL, NULL, ews__AddImGroup, _param_84); }
	virtual	int AddImGroup(const char *endpoint, const char *soap_action, ews__AddImGroupType *ews__AddImGroup, struct __ews__AddImGroupResponse &_param_84);

	/// Web service operation 'AddDistributionGroupToImList' (returns error code or SOAP_OK)
	virtual	int AddDistributionGroupToImList(ews__AddDistributionGroupToImListType *ews__AddDistributionGroupToImList, struct __ews__AddDistributionGroupToImListResponse &_param_85) { return this->AddDistributionGroupToImList(NULL, NULL, ews__AddDistributionGroupToImList, _param_85); }
	virtual	int AddDistributionGroupToImList(const char *endpoint, const char *soap_action, ews__AddDistributionGroupToImListType *ews__AddDistributionGroupToImList, struct __ews__AddDistributionGroupToImListResponse &_param_85);

	/// Web service operation 'GetImItemList' (returns error code or SOAP_OK)
	virtual	int GetImItemList(ews__GetImItemListType *ews__GetImItemList, struct __ews__GetImItemListResponse &_param_86) { return this->GetImItemList(NULL, NULL, ews__GetImItemList, _param_86); }
	virtual	int GetImItemList(const char *endpoint, const char *soap_action, ews__GetImItemListType *ews__GetImItemList, struct __ews__GetImItemListResponse &_param_86);

	/// Web service operation 'GetImItems' (returns error code or SOAP_OK)
	virtual	int GetImItems(ews__GetImItemsType *ews__GetImItems, struct __ews__GetImItemsResponse &_param_87) { return this->GetImItems(NULL, NULL, ews__GetImItems, _param_87); }
	virtual	int GetImItems(const char *endpoint, const char *soap_action, ews__GetImItemsType *ews__GetImItems, struct __ews__GetImItemsResponse &_param_87);

	/// Web service operation 'RemoveContactFromImList' (returns error code or SOAP_OK)
	virtual	int RemoveContactFromImList(ews__RemoveContactFromImListType *ews__RemoveContactFromImList, struct __ews__RemoveContactFromImListResponse &_param_88) { return this->RemoveContactFromImList(NULL, NULL, ews__RemoveContactFromImList, _param_88); }
	virtual	int RemoveContactFromImList(const char *endpoint, const char *soap_action, ews__RemoveContactFromImListType *ews__RemoveContactFromImList, struct __ews__RemoveContactFromImListResponse &_param_88);

	/// Web service operation 'RemoveDistributionGroupFromImList' (returns error code or SOAP_OK)
	virtual	int RemoveDistributionGroupFromImList(ews__RemoveDistributionGroupFromImListType *ews__RemoveDistributionGroupFromImList, struct __ews__RemoveDistributionGroupFromImListResponse &_param_89) { return this->RemoveDistributionGroupFromImList(NULL, NULL, ews__RemoveDistributionGroupFromImList, _param_89); }
	virtual	int RemoveDistributionGroupFromImList(const char *endpoint, const char *soap_action, ews__RemoveDistributionGroupFromImListType *ews__RemoveDistributionGroupFromImList, struct __ews__RemoveDistributionGroupFromImListResponse &_param_89);

	/// Web service operation 'RemoveImGroup' (returns error code or SOAP_OK)
	virtual	int RemoveImGroup(ews__RemoveImGroupType *ews__RemoveImGroup, struct __ews__RemoveImGroupResponse &_param_90) { return this->RemoveImGroup(NULL, NULL, ews__RemoveImGroup, _param_90); }
	virtual	int RemoveImGroup(const char *endpoint, const char *soap_action, ews__RemoveImGroupType *ews__RemoveImGroup, struct __ews__RemoveImGroupResponse &_param_90);

	/// Web service operation 'SetImGroup' (returns error code or SOAP_OK)
	virtual	int SetImGroup(ews__SetImGroupType *ews__SetImGroup, struct __ews__SetImGroupResponse &_param_91) { return this->SetImGroup(NULL, NULL, ews__SetImGroup, _param_91); }
	virtual	int SetImGroup(const char *endpoint, const char *soap_action, ews__SetImGroupType *ews__SetImGroup, struct __ews__SetImGroupResponse &_param_91);

	/// Web service operation 'SetImListMigrationCompleted' (returns error code or SOAP_OK)
	virtual	int SetImListMigrationCompleted(ews__SetImListMigrationCompletedType *ews__SetImListMigrationCompleted, struct __ews__SetImListMigrationCompletedResponse &_param_92) { return this->SetImListMigrationCompleted(NULL, NULL, ews__SetImListMigrationCompleted, _param_92); }
	virtual	int SetImListMigrationCompleted(const char *endpoint, const char *soap_action, ews__SetImListMigrationCompletedType *ews__SetImListMigrationCompleted, struct __ews__SetImListMigrationCompletedResponse &_param_92);

	/// Web service operation 'GetUserRetentionPolicyTags' (returns error code or SOAP_OK)
	virtual	int GetUserRetentionPolicyTags(ews__GetUserRetentionPolicyTagsType *ews__GetUserRetentionPolicyTags, struct __ews__GetUserRetentionPolicyTagsResponse &_param_93) { return this->GetUserRetentionPolicyTags(NULL, NULL, ews__GetUserRetentionPolicyTags, _param_93); }
	virtual	int GetUserRetentionPolicyTags(const char *endpoint, const char *soap_action, ews__GetUserRetentionPolicyTagsType *ews__GetUserRetentionPolicyTags, struct __ews__GetUserRetentionPolicyTagsResponse &_param_93);

	/// Web service operation 'DisableApp' (returns error code or SOAP_OK)
	virtual	int DisableApp(ews__DisableAppType *ews__DisableApp, struct __ews__DisableAppResponse &_param_94) { return this->DisableApp(NULL, NULL, ews__DisableApp, _param_94); }
	virtual	int DisableApp(const char *endpoint, const char *soap_action, ews__DisableAppType *ews__DisableApp, struct __ews__DisableAppResponse &_param_94);

	/// Web service operation 'InstallApp' (returns error code or SOAP_OK)
	virtual	int InstallApp(ews__InstallAppType *ews__InstallApp, struct __ews__InstallAppResponse &_param_95) { return this->InstallApp(NULL, NULL, ews__InstallApp, _param_95); }
	virtual	int InstallApp(const char *endpoint, const char *soap_action, ews__InstallAppType *ews__InstallApp, struct __ews__InstallAppResponse &_param_95);

	/// Web service operation 'UninstallApp' (returns error code or SOAP_OK)
	virtual	int UninstallApp(ews__UninstallAppType *ews__UninstallApp, struct __ews__UninstallAppResponse &_param_96) { return this->UninstallApp(NULL, NULL, ews__UninstallApp, _param_96); }
	virtual	int UninstallApp(const char *endpoint, const char *soap_action, ews__UninstallAppType *ews__UninstallApp, struct __ews__UninstallAppResponse &_param_96);

	/// Web service operation 'GetAppMarketplaceUrl' (returns error code or SOAP_OK)
	virtual	int GetAppMarketplaceUrl(ews__GetAppMarketplaceUrlType *ews__GetAppMarketplaceUrl, struct __ews__GetAppMarketplaceUrlResponse &_param_97) { return this->GetAppMarketplaceUrl(NULL, NULL, ews__GetAppMarketplaceUrl, _param_97); }
	virtual	int GetAppMarketplaceUrl(const char *endpoint, const char *soap_action, ews__GetAppMarketplaceUrlType *ews__GetAppMarketplaceUrl, struct __ews__GetAppMarketplaceUrlResponse &_param_97);

	/// Web service operation 'GetUserPhoto' (returns error code or SOAP_OK)
	virtual	int GetUserPhoto(ews__GetUserPhotoType *ews__GetUserPhoto, struct __ews__GetUserPhotoResponse &_param_98) { return this->GetUserPhoto(NULL, NULL, ews__GetUserPhoto, _param_98); }
	virtual	int GetUserPhoto(const char *endpoint, const char *soap_action, ews__GetUserPhotoType *ews__GetUserPhoto, struct __ews__GetUserPhotoResponse &_param_98);

	/// Web service operation 'FindAvailableMeetingTimes' (returns error code or SOAP_OK)
	virtual	int FindAvailableMeetingTimes(ews__FindAvailableMeetingTimesType *ews__FindAvailableMeetingTimes, struct __ews__FindAvailableMeetingTimesResponse &_param_99) { return this->FindAvailableMeetingTimes(NULL, NULL, ews__FindAvailableMeetingTimes, _param_99); }
	virtual	int FindAvailableMeetingTimes(const char *endpoint, const char *soap_action, ews__FindAvailableMeetingTimesType *ews__FindAvailableMeetingTimes, struct __ews__FindAvailableMeetingTimesResponse &_param_99);

	/// Web service operation 'SetUserPhoto' (returns error code or SOAP_OK)
	virtual	int SetUserPhoto(ews__SetUserPhotoType *ews__SetUserPhoto, struct __ews__SetUserPhotoResponse &_param_100) { return this->SetUserPhoto(NULL, NULL, ews__SetUserPhoto, _param_100); }
	virtual	int SetUserPhoto(const char *endpoint, const char *soap_action, ews__SetUserPhotoType *ews__SetUserPhoto, struct __ews__SetUserPhotoResponse &_param_100);
};
#endif
